# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cashFlow_pb2 as cashFlow__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cashFlow_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CashFlowServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCategory = channel.unary_unary(
                '/cashFlow.CashFlowService/CreateCategory',
                request_serializer=cashFlow__pb2.CreateCategoryRequest.SerializeToString,
                response_deserializer=cashFlow__pb2.CreateCategoryResponse.FromString,
                _registered_method=True)
        self.CreateAccountType = channel.unary_unary(
                '/cashFlow.CashFlowService/CreateAccountType',
                request_serializer=cashFlow__pb2.CreateAccountTypeRequest.SerializeToString,
                response_deserializer=cashFlow__pb2.CreateAccountTypeResponse.FromString,
                _registered_method=True)
        self.CreateAccount = channel.unary_unary(
                '/cashFlow.CashFlowService/CreateAccount',
                request_serializer=cashFlow__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=cashFlow__pb2.CreateAccountResponse.FromString,
                _registered_method=True)
        self.CreateInflow = channel.unary_unary(
                '/cashFlow.CashFlowService/CreateInflow',
                request_serializer=cashFlow__pb2.CreateInflowRequest.SerializeToString,
                response_deserializer=cashFlow__pb2.CreateInflowResponse.FromString,
                _registered_method=True)
        self.CreateOutflow = channel.unary_unary(
                '/cashFlow.CashFlowService/CreateOutflow',
                request_serializer=cashFlow__pb2.CreateOutflowRequest.SerializeToString,
                response_deserializer=cashFlow__pb2.CreateOutflowResponse.FromString,
                _registered_method=True)


class CashFlowServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccountType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateInflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOutflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CashFlowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCategory,
                    request_deserializer=cashFlow__pb2.CreateCategoryRequest.FromString,
                    response_serializer=cashFlow__pb2.CreateCategoryResponse.SerializeToString,
            ),
            'CreateAccountType': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccountType,
                    request_deserializer=cashFlow__pb2.CreateAccountTypeRequest.FromString,
                    response_serializer=cashFlow__pb2.CreateAccountTypeResponse.SerializeToString,
            ),
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=cashFlow__pb2.CreateAccountRequest.FromString,
                    response_serializer=cashFlow__pb2.CreateAccountResponse.SerializeToString,
            ),
            'CreateInflow': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInflow,
                    request_deserializer=cashFlow__pb2.CreateInflowRequest.FromString,
                    response_serializer=cashFlow__pb2.CreateInflowResponse.SerializeToString,
            ),
            'CreateOutflow': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOutflow,
                    request_deserializer=cashFlow__pb2.CreateOutflowRequest.FromString,
                    response_serializer=cashFlow__pb2.CreateOutflowResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cashFlow.CashFlowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cashFlow.CashFlowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CashFlowService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cashFlow.CashFlowService/CreateCategory',
            cashFlow__pb2.CreateCategoryRequest.SerializeToString,
            cashFlow__pb2.CreateCategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAccountType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cashFlow.CashFlowService/CreateAccountType',
            cashFlow__pb2.CreateAccountTypeRequest.SerializeToString,
            cashFlow__pb2.CreateAccountTypeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cashFlow.CashFlowService/CreateAccount',
            cashFlow__pb2.CreateAccountRequest.SerializeToString,
            cashFlow__pb2.CreateAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateInflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cashFlow.CashFlowService/CreateInflow',
            cashFlow__pb2.CreateInflowRequest.SerializeToString,
            cashFlow__pb2.CreateInflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOutflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cashFlow.CashFlowService/CreateOutflow',
            cashFlow__pb2.CreateOutflowRequest.SerializeToString,
            cashFlow__pb2.CreateOutflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
