[project]
name = "api_gateway"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "shared_proto",
]

[project.scripts]
api_gateway = "api_gateway:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
shared_proto = { workspace = true }
